app:
  file: init.lua

credentials:
  users:
    serveruser:
      password: "fuck"
      privileges:
      - permissions: [ read, write ]
        spaces: [ sessions, joinedusers ] 

groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
